# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51fd90f4e8761bd443a2a6e5fe122a7f62612c0796155b9b09f3b551ec933c958963f68bcf941f25997c80497dbe141d255bf63ee9d07d27bfb8157d9a793e19

test:
  secret_key_base: d55c4824d896543658c5f678433ec11fa0a84ce959c9d1e5d0baf3bfe89bd9b54ab5f1d5fba4f7c2e122ba3659aa7589356cb6a98fc18ae62aca45a510e19caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
